FlaUI/FlaUI

src/FlaUI.Core/Elements/Infrastructure/Element.cs
src/FlaUI.Core/FlaUI.Core.csproj
src/FlaUI.Core/Tools/Retry.cs

This adds a retry loop when attempting to get an element so that the user can set a timeout period. This mirrors the functionality in white and selenium. This is the third pull which takes into consideration the UIA2 and UIA3 changes.

Adds retry loop when attempting to get an element

---

src/FlaUI.Core.UITests/Converters/ValueConverterTests.cs
src/FlaUI.Core.UITests/FlaUI.Core.UITests.csproj
src/FlaUI.UIA2/Converters/ValueConverter.cs
src/FlaUI.UIA2/Identifiers/AutomationObjectIds.cs

The value converter was throwing when attempting to convert UIA2 type to FlaUI enums. Copied the UIA3 converters method of conversion for the UIA2 code except I had to use a if block since the UIA2 types are not static values.

Adds control type value converter to UIA2

---

src/FlaUI.UIA2/UIA2BasicAutomationElement.cs

When we use UIA2 and try to register property change event ,property is missing.
I have added the missed parameter.

fix - RegisterPropertyChangedEvent property missing

---

src/FlaUI.Core.UITests/CaptureTests.cs
src/FlaUI.Core/AutomationElements/Infrastructure/AutomationElement.cs
src/FlaUI.Core/Capture.cs

SetForeground can only be used for windows. If a capture of a control is required it must use Focus instead of SetForeground.

Fixed missing WindowHandle on Capture, changed Focus and SetForeground comments

---

src/FlaUI.Core.UITests/XPathTests.cs
src/FlaUI.Core/AutomationElementXPathNavigator.cs
src/FlaUI.Core/Definitions/ControlType.cs

Fixes Issue #170 (and is a first step towards fixing Issue #121) by adding a default value called 'Unknown' to the ControlTpe enum.
This value is returned by TryGetValue() as well as GetValueOrDefault when the underlying library cannot determine the real control type.

 Default value for the ControlType enum. Fixes Issue #170

---

src/FlaUI.Core/AutomationElements/PatternElements/ExpandCollapseAutomationElement.cs

I'm assuming this was a copy+paste issue or just a small slipup, but the `Collapse` function of all ExpandCollapseAutomationElements is actually calling the `Expand` function of the ExpandCollapsePattern.

Switch Collapse function to correctly call the Collapse function of the expand pattern

---

src/FlaUI.Core.UITests/Elements/DataGridViewTests.cs
src/FlaUI.Core.UITests/Patterns/GridPatternTests.cs
src/FlaUI.Core/AutomationElements/DataGridView.cs
src/TestApplications/WpfApplication/DataGridItem.cs
src/TestApplications/WpfApplication/MainViewModel.cs
src/TestApplications/WpfApplication/MainWindow.xaml

This PR addresses several issues I've noticed with interacting with WPF DataGrids.
Specifically:
- `DataGridView.Rows` always returns an empty array
- `DataGridViewRow.Cells` returns too many items (doesn't filter out the header cell)
- `DataGridView.Header` always returns null
All changes in the first commit are related to making the test WpfApplication's DataGrid control match the winforms version so tests are valid against either application type. I have tried to ensure no regressions were introduced with WinForm DataGrids.
I wasn't able to find any sort of style guide, so let me know if any code styling changes need to be made.

Improve DataGrid support for WPF apps

---

src/FlaUI.Core/Capturing/InfoOverlay.cs

It would be nice to have the option to change the font of InfoOverlay text when capturing images/videos. My proposal works the same way as the coloring of the text. The default stays the same.

InfoOverlay font property added.

---

src/FlaUI.Core/Capturing/CaptureUtilities.cs

I discovered this GDI handle leak when I try to capture screenshot with a MouseOverlay repeatedly. Eventually the process will reach the 100,000 GDI handle limit and throw an exception `System.Runtime.InteropServices.COMException: System.Runtime.InteropServices.COMException: MILERR_WIN32ERROR (Exception from HRESULT: 0x88980003).`

fixed GDI handle leak in CaptureCursor

---

src/FlaUI.Core/Application.cs
src/FlaUI.Core/FlaUI.Core.csproj
src/FlaUI.UIA2/FlaUI.UIA2.csproj
src/FlaUI.UIA3/FlaUI.UIA3.csproj

Hi! Great framework, I wanted to use this in combination with another .NET Core 3.1 library, hence the pull request!
Added .NET Core 3.1 as a target framework, did it the same way as it was done with .NET Core 3.0.
Added a fix for Application.cs where the process had to be created again to get a valid MainWindowHandle. The MainWindowHandle has a bug where it is evaluated once, and then it has that pointer forever. If it is evaluated early it will get a IntPtr.Zero resulting in us never getting a valid value. I've seen a lot of people write about this and it should be fixed when we get a new nuget package for System.Diagnostics.Process.
The issue with MainWindowHandle, ProcessManager.GetMainWindowHandle(_processId) can return IntPtr.Zero.
```csharp
public IntPtr MainWindowHandle
{
get
{
if …
```

Add .Net Core 3.1 as build target & Fix for Process.MainWindowHandle

---

src/FlaUI.Core/Conditions/ConditionFactory.cs

-  add optional `PropertyConditionFlags `parameter to string-based conditions (like `ByName` or `ByValue`)
---
This way you can use 
`ConditionFactory.ByName("test", PropertyConditionFlags.MatchSubstring)`
to match elements with names like "test123".

Extend ConditionFactory

---

src/FlaUI.TestUtilities/FlaUITestBase.cs

Let inheritors set Application property so that it can be set when using ApplicationStartMode.None

Change property from private set to protected set

---

src/FlaUI.TestUtilities/FlaUITestBase.cs

Make the public methods in FlaUITestBase virtual in case inheritors needs to modify them

Make FlaUITestBase easier to customize for subclasses

---

src/FlaUI.Core/Input/Mouse.cs

**Problem:** `RightDoubleClick()` method in `Mouse` class contains a mistype, so it is actually performs `LeftDoubleClick()`.
**Proposed fix:** Change `MouseButton` to `Right` to fix copy-paste issue.
**Description:**
I noticed a copy-paste issue in `Mouse` class while investigating the code online. Taking into account that `RightDoubleClick()` implementation seems to be wrong, I created this PR to fix this small issue.

Fix mistype in `RightDoubleClick()` mouse method

---

src/FlaUI.Core/Input/Keyboard.cs
src/FlaUI.Core/Input/Mouse.cs

This would solve https://github.com/FlaUI/FlaUI/issues/437 for us. I adapted the code to throw an error like all the other places that check `GetLastWin32Error`.

Throw exception instead of hiding the error

---

src/FlaUI.Core/Capturing/VideoRecorder.cs
src/FlaUI.Core/Capturing/VideoRecorderSettings.cs

In our case it adds too much info in test logs, due to the high
framerate used.

Allow to skip logging missing frames info

---

src/FlaUI.TestUtilities/FlaUITestBase.cs

[[L143-L145]](https://github.com/igorrecioh/FlaUI/blob/3dafb2092f333a6928eae6d2a9fbd8bad341440b/src/FlaUI.TestUtilities/FlaUITestBase.cs#L143-L145) I have added the AddTestAttachment method in order to include taken screenshot to the report and, therefore, the screenshot will be available in XML report, generated at the end of execution. This is interesting when parsing XML to generate, for example, an HTML report.
[[L278-L286]](https://github.com/igorrecioh/FlaUI/blob/3dafb2092f333a6928eae6d2a9fbd8bad341440b/src/FlaUI.TestUtilities/FlaUITestBase.cs#L278-L286) I have extracted from TakeScreenShot the generation of the full path so that I can use it in previously explained code.

Add screenshot to testresult for XML report

---

src/FlaUI.Core/Input/Keyboard.cs

There's an issue we're seeing with triggering tooltips within text boxes: we're trying to enter invalid characters into a text box, and then verify that an error tooltip appears. Usually the tooltip will remain on screen for awhile after entering the character, but using FlaUI we found that it will instead appear very briefly before disappearing again.
Here is a GIF of this happening, where we're entering a series of invalid characters into a text box using FlaUI. As you can see, the tooltip disappears very quickly. This is causing problems as we're trying to capture the tooltip and its contents, but this is difficult since there's only a brief window to do so.
After some testing, I found that this happens when typing a character that requires modifiers to be pressed, and that the lack of …

Add delay after pressing keyboard modifiers

---

src/FlaUI.TestUtilities/FlaUITestBase.cs

It could be interesting to have the option of enabling or disabling the screenshots capture when a test fails. However, this can be transparent for everyone as, by default, it keeps activated. If anyone needs to disable it (as it is my case), the property can be overriden.

Added new flag to define usage of screenshots

---

src/FlaUI.Core/AutomationElements/ComboBox.cs

Filter only ListItem control types when getting Items from combobox.
Reason: On a ComboBox with many items, the first child might be the vertical scroll bar, which must be eliminated from the items list.

Combobox verify list item

---

LICENSE.txt
src/FlaUI.Core/FlaUI.Core.csproj
src/FlaUI.TestUtilities/FlaUI.TestUtilities.csproj
src/FlaUI.UIA2/FlaUI.UIA2.csproj
src/FlaUI.UIA3/FlaUI.UIA3.csproj

Small change to bump up the copyright year from 2024 to 2025.

Increment copyright year

---

src/FlaUI.Core/Extensions/ScrollPatternExtensions.cs
src/FlaUI.Core/Patterns/ScrollPattern.cs

It's often the case where you need to scroll only horizontally or vertically, rather than both at the same time. In order to make this a bit easier to do, I've added some additional methods for scrolling just one way or the other. This saves the caller from having to always use `ScrollAmount.NoAmount` or `ScrollPatternConstants.NoScroll` for one of the parameters whenever the `Scroll` and `SetScrollPercent` methods are used.

Add horizontal and vertical scroll methods

---

src/FlaUI.Core/Capturing/VideoRecorder.cs

**Describe the bug**
During an automation test, we modify the system date to a later date, do some tests, than change it back to the original.
After the second modification, where the system date was changed to an earlier time (with 1 hour), the recording seemingly stopped, but in reality, it was delayed for 1 hour.
**Reproducibility**
Start a recording and set the system date back by 1 hour.
The next time when the recording task will calculate the necessary delay before the next capture, the calculated delay will be approximately 1 hour.
Since the safety check only begates negative timestamps, the Task.Delay will be performed and the recording will be stopped (delayed).
**Code snippets**
_FlaUI.Core.Capturing.VideoRecorder.RecordLoop()_
var timestamp = DateTime.UtcNow;
... actual …

Handle incorrect time offset when system time changes during recording

---

src/FlaUI.Core.UITests/XPathTests.cs
src/FlaUI.Core/AutomationElementXPathNavigator.cs

Problem:
If the element tree has elements that don't have specific attributes (e.g. "Name"), when you use an XPath query containing a function, such as "contains" that attempts to access that attribute, FlaUI will exception.
Resolution:
XPathNavigator expects non-null values.  Modified code to return empty strings, rather than null values.
Added unit test to cover scenario.

Fix XPath exceptions when using XPath functions on attributes that may not exist on elements
